# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beequick', '0005_foodtypes_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='market',
            new_name='marketprice',
        ),
    ]
